### ISSUE TITLE
TodoMVC: interest in listing on the site?

### ISSUE THREAD

**Issue by addyosmani** [googlearchive/projects#12]
If there's ever interest, I'd be happy to consider including a Polymer-based TodoMVC app (you have 4 variants) in the Labs category of apps on our homepage at todomvc.com.

This is typically for frameworks that are still under heavy development but could give developers interested in comparing Polymer to other frameworks some awareness that one built using this is available :)

**Comment by jkomoros** [comment]
Sounds great to me!

**Comment by sjmiles** [comment]
Thanks Addy, we definitely would like some representation there. The hesitation so far comes from not knowing which facets would be best to highlight. The reason there are so many variants is because different styles appeal to different audiences and we wanted to explore some of these choices.

In other words, I'm nervous of supplying a canonical TodoMVC version and having N people decide Polymer is not for them because of some design choice in that particular application that does not come from Polymer proper. 

I imagine the answer is 'tough beans' and we should just do the best we can. :)

**Comment by addyosmani** [comment]
I think we might have a partial solution to this :) Over the weekend we introduced a new information bar for our Todo implementations which allows apps to list different versions of the same application. All versions are given the same visibility and we just require that a readme describing the difference between the various versions is made available:

![screen shot 2013-05-18 at 16 55 06](https://f.cloud.github.com/assets/110953/537675/de1428a4-c177-11e2-9a04-b32182e6fb02.png)

I could imagine Polymer having the four different variants listed in the top corner. As this app falls into the Labs category for now, I absolutely don't mind us including all variations until you're happy with the design choices you'd like to encourage. We're happy to include Polymer Todo apps in this form or wait until such a time that you're more comfortable with it being on the site :)

**Comment by sjmiles** [comment]
Thanks Addy. I don't think we need all four :), but this seems like a great
feature.

We are discussing the options right now.

**Comment by addyosmani** [comment]
Closing as this is now live :)
